version: "3.12.3"

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/django
    image: app:django
    container_name: docker_project_container
    command: python manage.py runserver 0.0.0.0:8000
  

